#!/usr/bin/env python3
"""Add Daily Economic News navigation and Nasdaq fund-limit status page."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "docs" / "index.html"
MARKER = "DAILY_NEWS_NASDAQ_LIMITS_UI"

CSS = r'''
/* DAILY_NEWS_NASDAQ_LIMITS_UI */
.sr-news-panel,.sr-nasdaq-panel{display:none;padding:18px 20px;margin-bottom:14px}
body[data-nav-page="news"] #srDailyNewsPanel{display:block!important}
body[data-nav-page="nasdaq-limits"] #srNasdaqLimitsPanel{display:block!important}
.primary-item[data-primary="news"] .primary-icon{color:#63b3ed}.sr-news-subnav{margin:1px 0 7px 13px;padding:3px 0 4px 10px;border-left:1px solid rgba(255,255,255,.09);display:flex;flex-direction:column;gap:2px}.sr-news-subnav[hidden]{display:none}.sr-news-subnav button{padding:7px 9px!important;font-size:11px!important;border-radius:7px!important}.sr-news-subnav button.active{background:color-mix(in srgb,var(--blue) 28%,transparent)!important;color:#fff!important}.sr-nasdaq-limit-nav{margin-left:16px!important;width:calc(100% - 16px)!important;color:#a9c4ff!important}.sr-nasdaq-limit-nav.active{background:color-mix(in srgb,var(--blue) 30%,transparent)!important;color:#fff!important}
.sr-page-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;margin-bottom:14px}.sr-page-head h3{margin:0;font-size:20px}.sr-page-head p{margin:5px 0 0;color:var(--muted);font-size:11px;line-height:1.7;max-width:820px}.sr-page-updated{color:var(--muted);font-size:10px;white-space:nowrap}
.sr-news-tabs{display:flex;gap:7px;flex-wrap:wrap;margin:0 0 14px}.sr-news-tab{border:1px solid var(--line);background:var(--paper);color:var(--ink);border-radius:999px;padding:7px 11px;font-size:10px;font-weight:800;cursor:pointer}.sr-news-tab.active{background:var(--blue);border-color:var(--blue);color:#fff}.sr-news-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.sr-news-card{border:1px solid var(--line);background:var(--paper);border-radius:11px;padding:12px 13px;min-width:0}.sr-news-meta{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-bottom:7px;color:var(--muted);font-size:9px}.sr-news-cat{display:inline-flex;padding:3px 7px;border-radius:999px;background:var(--blue2);color:var(--blue);font-weight:850}.sr-news-title{display:block;color:var(--ink);font-size:12px;font-weight:800;line-height:1.55;text-decoration:none}.sr-news-title:hover{color:var(--blue)}.sr-news-source{margin-top:8px;color:var(--muted);font-size:9px}.sr-news-empty{grid-column:1/-1;padding:28px;text-align:center;border:1px dashed var(--line);border-radius:11px;color:var(--muted);font-size:11px}
.sr-nasdaq-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-bottom:13px}.sr-nasdaq-kpi{border:1px solid var(--line);background:var(--paper);border-radius:10px;padding:11px}.sr-nasdaq-kpi span{display:block;color:var(--muted);font-size:9px}.sr-nasdaq-kpi strong{display:block;margin-top:5px;font-size:18px}.sr-nasdaq-controls{display:flex;gap:8px;align-items:center;margin:0 0 12px;flex-wrap:wrap}.sr-nasdaq-controls input,.sr-nasdaq-controls select{height:34px;border:1px solid var(--line);border-radius:8px;background:var(--paper);color:var(--ink);padding:0 10px;font-size:10px}.sr-nasdaq-controls input{min-width:220px;flex:1}.sr-nasdaq-table-wrap{overflow:auto;border:1px solid var(--line);border-radius:11px}.sr-nasdaq-table{width:100%;border-collapse:collapse;min-width:900px;background:var(--paper)}.sr-nasdaq-table th,.sr-nasdaq-table td{padding:10px 11px;border-bottom:1px solid var(--line);text-align:left;font-size:10px;vertical-align:middle}.sr-nasdaq-table th{position:sticky;top:0;background:color-mix(in srgb,var(--paper) 94%,var(--bg));color:var(--muted);font-size:9px;z-index:1}.sr-nasdaq-table tr:last-child td{border-bottom:0}.sr-fund-name{font-weight:800;color:var(--ink);max-width:290px}.sr-status{display:inline-flex;border-radius:999px;padding:4px 7px;font-size:9px;font-weight:850;white-space:nowrap}.sr-status.limited{background:#fff4d8;color:#8a5d00}.sr-status.paused{background:#fff0ef;color:#a33a31}.sr-status.open{background:#ecfdf3;color:#087443}.sr-status.exchange{background:var(--blue2);color:var(--blue)}.sr-status.unknown{background:var(--bg);color:var(--muted)}.sr-limit-value{font-weight:850;font-variant-numeric:tabular-nums}.sr-source-link{color:var(--blue);text-decoration:none}.sr-source-link:hover{text-decoration:underline}.sr-nasdaq-note{margin-top:10px;color:var(--muted);font-size:9px;line-height:1.65}.sr-nasdaq-context{display:inline-flex;margin-top:8px;border:1px solid var(--line);background:var(--paper);color:var(--blue);border-radius:8px;padding:7px 10px;font-size:10px;font-weight:850;cursor:pointer}.sr-nasdaq-context:hover{border-color:var(--blue);background:var(--blue2)}
@media(max-width:900px){.sr-news-list{grid-template-columns:1fr}.sr-nasdaq-summary{grid-template-columns:1fr 1fr}}
@media(max-width:760px){.sr-news-panel,.sr-nasdaq-panel{padding:14px}.sr-page-head{display:block}.sr-page-updated{margin-top:7px}.sr-nasdaq-controls{display:grid;grid-template-columns:1fr 1fr}.sr-nasdaq-controls input{grid-column:1/-1;min-width:0;width:100%}}
'''

JS = r'''
// DAILY_NEWS_NASDAQ_LIMITS_UI
const srNewsCategories=['科技','医药','机器人','煤炭','新能源','消费','金融'];
let srNewsCategory='科技';
let srNewsExpanded=true;
try{srNewsExpanded=localStorage.getItem('sectorRadarNewsExpandedV1')!=='0'}catch(_e){}
let srNewsData=null,srNewsPromise=null,srNasdaqData=null,srNasdaqPromise=null,srNasdaqStatus='all',srNasdaqQuery='';
function srNewsHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function srNewsSafeUrl(v){try{const u=new URL(String(v||''),location.href);return ['http:','https:'].includes(u.protocol)?u.href:'#'}catch(_e){return'#'}}
function srNewsFmtTime(v){if(!v)return'—';const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v).slice(0,16);return d.toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})}
function srNewsEnsurePanels(){const top=document.querySelector('.topbar');if(!document.getElementById('srDailyNewsPanel')){const p=document.createElement('section');p.id='srDailyNewsPanel';p.className='panel sr-news-panel';p.innerHTML=`<div class="sr-page-head"><div><h3>每日经济新闻</h3><p>按产业主题聚合公开财经媒体的最新标题。只展示标题、来源、发布时间和原文入口，不整篇转载；用于快速了解行业动态，不代表投资排序。</p></div><div class="sr-page-updated" id="srNewsUpdated">数据加载中…</div></div><div class="sr-news-tabs" id="srNewsTabs"></div><div class="sr-news-list" id="srNewsList"><div class="sr-news-empty">正在读取最新新闻…</div></div>`;top?top.after(p):document.querySelector('.content')?.prepend(p)}if(!document.getElementById('srNasdaqLimitsPanel')){const p=document.createElement('section');p.id='srNasdaqLimitsPanel';p.className='panel sr-nasdaq-panel';p.innerHTML=`<div class="sr-page-head"><div><h3>纳斯达克基金 · 申购限额最新情况</h3><p>扫描名称含“纳斯达克 / 纳指 / NASDAQ”的公开基金目录，并读取基金档案中的最新申购状态和单日限额。限额变化频繁，最终以基金公司最新公告为准。</p></div><div class="sr-page-updated" id="srNasdaqUpdated">数据加载中…</div></div><div class="sr-nasdaq-summary" id="srNasdaqSummary"></div><div class="sr-nasdaq-controls"><input id="srNasdaqSearch" placeholder="搜索基金名称或代码"><select id="srNasdaqStatus"><option value="all">全部状态</option><option value="暂停申购">暂停申购</option><option value="限大额">限大额</option><option value="开放申购">开放申购</option><option value="场内交易">场内交易</option><option value="待核对">待核对</option></select></div><div class="sr-nasdaq-table-wrap"><table class="sr-nasdaq-table"><thead><tr><th>基金</th><th>代码</th><th>类型</th><th>申购状态</th><th>单日限额</th><th>最新净值</th><th>来源</th></tr></thead><tbody id="srNasdaqRows"><tr><td colspan="7">正在读取最新基金状态…</td></tr></tbody></table></div><div class="sr-nasdaq-note" id="srNasdaqNote">场内ETF通过交易所买卖，与场外基金“单日申购限额”不是同一概念；页面会单独标记“场内交易”。</div>`;top?top.after(p):document.querySelector('.content')?.prepend(p)}}
async function srLoadNews(){if(srNewsData)return srNewsData;if(srNewsPromise)return srNewsPromise;srNewsPromise=fetch('data/daily_news.json?ts='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}).then(x=>(srNewsData=x)).catch(e=>({error:String(e),categories:{}}));return srNewsPromise}
async function srLoadNasdaq(){if(srNasdaqData)return srNasdaqData;if(srNasdaqPromise)return srNasdaqPromise;srNasdaqPromise=fetch('data/nasdaq_fund_limits.json?ts='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}).then(x=>(srNasdaqData=x)).catch(e=>({error:String(e),funds:[]}));return srNasdaqPromise}
function srRenderNewsTabs(){const box=document.getElementById('srNewsTabs');if(!box)return;box.innerHTML=['全部',...srNewsCategories].map(c=>`<button type="button" class="sr-news-tab ${srNewsCategory===c?'active':''}" data-news-tab="${srNewsHtml(c)}">${srNewsHtml(c)}</button>`).join('');box.querySelectorAll('[data-news-tab]').forEach(b=>b.onclick=()=>{srNewsCategory=b.dataset.newsTab;srRenderDailyNews()})}
async function srRenderDailyNews(){srNewsEnsurePanels();srRenderNewsTabs();const box=document.getElementById('srNewsList');if(box)box.innerHTML='<div class="sr-news-empty">正在读取最新新闻…</div>';const data=await srLoadNews(),cats=data?.categories||{};const updated=document.getElementById('srNewsUpdated');if(updated)updated.textContent=data?.updated_at?`更新 ${srNewsFmtTime(data.updated_at)}`:'更新时间 —';let rows=[];if(srNewsCategory==='全部'){Object.values(cats).forEach(x=>{if(Array.isArray(x))rows.push(...x)});rows.sort((a,b)=>String(b.published_at||'').localeCompare(String(a.published_at||'')));rows=rows.slice(0,30)}else rows=Array.isArray(cats[srNewsCategory])?cats[srNewsCategory]:[];if(!box)return;if(!rows.length){box.innerHTML=`<div class="sr-news-empty">${data?.error?'新闻数据暂时读取失败':'当前分类暂无新闻'}，下一次自动构建会继续更新。</div>`;return}box.innerHTML=rows.map(x=>`<article class="sr-news-card"><div class="sr-news-meta"><span class="sr-news-cat">${srNewsHtml(x.category||srNewsCategory)}</span><span>${srNewsHtml(srNewsFmtTime(x.published_at))}</span></div><a class="sr-news-title" href="${srNewsHtml(srNewsSafeUrl(x.url))}" target="_blank" rel="noopener noreferrer">${srNewsHtml(x.title)}</a><div class="sr-news-source">来源：${srNewsHtml(x.source||'公开财经媒体')}</div></article>`).join('')}
function srNasdaqStatusClass(s){return s==='限大额'?'limited':s==='暂停申购'?'paused':s==='开放申购'?'open':s==='场内交易'?'exchange':'unknown'}
function srNasdaqRows(data){const q=srNasdaqQuery.trim().toLowerCase();return (data?.funds||[]).filter(x=>(srNasdaqStatus==='all'||x.status===srNasdaqStatus)&&(!q||`${x.name||''} ${x.code||''}`.toLowerCase().includes(q)))}
function srRenderNasdaqTable(data){const rows=srNasdaqRows(data),body=document.getElementById('srNasdaqRows');if(!body)return;if(!rows.length){body.innerHTML='<tr><td colspan="7">没有匹配的基金。</td></tr>';return}body.innerHTML=rows.map(x=>{const nav=x.nav?`${srNewsHtml(x.nav)}${x.nav_date?` <span class="empty">(${srNewsHtml(x.nav_date)})</span>`:''}`:'—';return `<tr><td class="sr-fund-name">${srNewsHtml(x.name)}</td><td>${srNewsHtml(x.code)}</td><td>${srNewsHtml(x.fund_type||'—')}</td><td><span class="sr-status ${srNasdaqStatusClass(x.status)}">${srNewsHtml(x.status||'待核对')}</span></td><td class="sr-limit-value">${srNewsHtml(x.limit_display||'—')}</td><td>${nav}</td><td><a class="sr-source-link" href="${srNewsHtml(srNewsSafeUrl(x.source_url))}" target="_blank" rel="noopener noreferrer">核对档案</a></td></tr>`}).join('')}
async function srRenderNasdaqLimits(){srNewsEnsurePanels();const body=document.getElementById('srNasdaqRows');if(body)body.innerHTML='<tr><td colspan="7">正在读取最新基金状态…</td></tr>';const data=await srLoadNasdaq(),updated=document.getElementById('srNasdaqUpdated');if(updated)updated.textContent=data?.updated_at?`更新 ${srNewsFmtTime(data.updated_at)}`:'更新时间 —';const sum=document.getElementById('srNasdaqSummary');if(sum)sum.innerHTML=`<div class="sr-nasdaq-kpi"><span>纳指相关基金</span><strong>${Number(data?.funds_total||0)}</strong></div><div class="sr-nasdaq-kpi"><span>限大额</span><strong>${Number(data?.limited_count||0)}</strong></div><div class="sr-nasdaq-kpi"><span>暂停申购</span><strong>${Number(data?.paused_count||0)}</strong></div><div class="sr-nasdaq-kpi"><span>已核对档案</span><strong>${Number(data?.checked_count||0)}</strong></div>`;const search=document.getElementById('srNasdaqSearch'),status=document.getElementById('srNasdaqStatus');if(search){search.value=srNasdaqQuery;search.oninput=()=>{srNasdaqQuery=search.value;srRenderNasdaqTable(data)}}if(status){status.value=srNasdaqStatus;status.onchange=()=>{srNasdaqStatus=status.value;srRenderNasdaqTable(data)}}const note=document.getElementById('srNasdaqNote');if(note&&data?.source_note)note.textContent=data.source_note+' 场内ETF通过交易所买卖，与场外基金单日申购限额不是同一概念。';srRenderNasdaqTable(data)}
function srEnsureNewsMobileOption(){const m=document.getElementById('mobilePrimaryNav');if(!m)return;if(!m.querySelector('option[value="news"]')){const o=document.createElement('option');o.value='news';o.textContent='每日经济新闻';const market=m.querySelector('option[value="market"]');market?m.insertBefore(o,market):m.appendChild(o)}if(navPage==='news')m.value='news';else if(navPage==='nasdaq-limits')m.value='all'}
function srInstallNewsNavigation(){const primary=document.querySelector('#menu .primary-nav');if(!primary)return;primary.querySelector('[data-primary="news"]')?.remove();primary.querySelector('.sr-news-subnav')?.remove();const market=primary.querySelector('[data-primary="market"]');const b=document.createElement('button');b.type='button';b.className=`primary-item ${navPage==='news'?'active':''} ${srNewsExpanded?'expanded':''}`;b.dataset.primary='news';b.innerHTML=`<span class="primary-main"><span class="primary-icon">▤</span>每日经济新闻</span><span><span class="primary-meta">每日更新</span> <span class="primary-caret">›</span></span>`;const sub=document.createElement('div');sub.className='sr-news-subnav';sub.hidden=!srNewsExpanded;sub.innerHTML=srNewsCategories.map(c=>`<button type="button" class="${navPage==='news'&&srNewsCategory===c?'active':''}" data-news-category="${srNewsHtml(c)}">${srNewsHtml(c)}</button>`).join('');b.onclick=()=>{srNewsExpanded=!srNewsExpanded;try{localStorage.setItem('sectorRadarNewsExpandedV1',srNewsExpanded?'1':'0')}catch(_e){}if(navPage!=='news')openNavPage('news');else buildMenu()};sub.querySelectorAll('[data-news-category]').forEach(x=>x.onclick=()=>{srNewsCategory=x.dataset.newsCategory;srNewsExpanded=true;openNavPage('news')});market?primary.insertBefore(b,market):primary.appendChild(b);market?primary.insertBefore(sub,market):primary.appendChild(sub);const nasdaq=primary.querySelector('[data-sector-name="纳斯达克"]');if(nasdaq){primary.querySelector('.sr-nasdaq-limit-nav')?.remove();const n=document.createElement('button');n.type='button';n.className=`sr-nasdaq-limit-nav ${navPage==='nasdaq-limits'?'active':''}`;n.innerHTML='<span>↳ 纳指基金限额最新情况</span><span class="mini">每日</span>';n.onclick=()=>openNavPage('nasdaq-limits');nasdaq.insertAdjacentElement('afterend',n)}if(navPage==='nasdaq-limits'){const all=primary.querySelector('[data-primary="all"]');all?.classList.add('active','expanded')}}
function srUpdateNasdaqContext(){document.getElementById('srNasdaqContext')?.remove();if(navPage!=='sector'||activeSector?.name!=='纳斯达克')return;const host=document.getElementById('benchmark')||document.querySelector('.hero-row > div');if(!host)return;const b=document.createElement('button');b.id='srNasdaqContext';b.type='button';b.className='sr-nasdaq-context';b.textContent='查看全部纳斯达克基金申购限额';b.onclick=()=>openNavPage('nasdaq-limits');host.appendChild(b)}
const srNewsBaseApplyNavVisibility=applyNavVisibility;
applyNavVisibility=function(){srNewsEnsurePanels();srEnsureNewsMobileOption();if(navPage==='news'){srNewsBaseApplyNavVisibility();srEnsureNewsMobileOption();setNavHeader('每日经济新闻','按科技、医药、机器人、煤炭等产业主题查看最新公开财经新闻。','DAILY ECONOMIC NEWS');srRenderDailyNews();return}if(navPage==='nasdaq-limits'){navAllExpanded=true;srNewsBaseApplyNavVisibility();srEnsureNewsMobileOption();setNavHeader('纳斯达克基金限额','查看纳指相关基金最新申购状态、单日限额和公开来源。','NASDAQ FUND LIMITS');srRenderNasdaqLimits();return}srNewsBaseApplyNavVisibility();srUpdateNasdaqContext()};
const srNewsBaseOpenNavPage=openNavPage;
openNavPage=function(page){if(page==='news'||page==='nasdaq-limits'){navPage=page;if(page==='nasdaq-limits')navAllExpanded=true;applyNavVisibility();buildMenu();window.scrollTo({top:0,behavior:'smooth'});return}srNewsBaseOpenNavPage(page)};
const srNewsBaseBuildMenu=buildMenu;
buildMenu=function(){srNewsBaseBuildMenu();srInstallNewsNavigation();srEnsureNewsMobileOption()};
const srNewsBaseBuildMobile=buildMobile;
buildMobile=function(){srNewsBaseBuildMobile();srEnsureNewsMobileOption();const p=document.getElementById('mobilePrimaryNav');if(p)p.onchange=()=>openNavPage(p.value)};
const srNewsBaseSelectSector=selectSector;
selectSector=function(name,push){srNewsBaseSelectSector(name,push);srUpdateNasdaqContext()};
srNewsEnsurePanels();srEnsureNewsMobileOption();buildMenu();srUpdateNasdaqContext();
'''


def main():
    text = INDEX.read_text(encoding="utf-8")
    if MARKER in text:
        print("[skip] daily news and Nasdaq limits UI already installed")
        return
    if "SECTOR_FAVORITES_WATCHLIST" not in text or "NAV_HOME_UI" not in text:
        raise RuntimeError("navigation and favorites UI must be installed first")
    if "</body>" not in text:
        raise RuntimeError("body marker missing")
    patch = f"\n<style>{CSS}</style>\n<script>{JS}</script>\n<!-- {MARKER} -->\n"
    text = text.replace("</body>", patch + "</body>", 1)
    INDEX.write_text(text, encoding="utf-8")
    print("[done] daily economic news + Nasdaq fund-limit navigation installed")


if __name__ == "__main__":
    main()
