#!/usr/bin/env python3
"""Replace the homepage with a mobile-first market overview dashboard."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "docs" / "index.html"
MARKER = "MARKET_HOME_DASHBOARD"

CSS = r"""
/* MARKET_HOME_DASHBOARD */
#homePanel{gap:14px}
.mh-index-strip{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}
.mh-index-card{border:1px solid var(--line);background:linear-gradient(145deg,color-mix(in srgb,var(--paper) 92%,var(--blue2)),var(--paper));border-radius:14px;padding:15px 16px;cursor:pointer;text-align:left;color:var(--ink);box-shadow:var(--shadow);position:relative;overflow:hidden}
.mh-index-card:after{content:"";position:absolute;inset:-45% auto auto 55%;width:55%;height:180%;transform:rotate(22deg);background:linear-gradient(90deg,transparent,rgba(255,255,255,.28),transparent);pointer-events:none}
.mh-index-card:hover{border-color:color-mix(in srgb,var(--blue) 45%,var(--line));transform:translateY(-1px)}
.mh-index-name{font-size:12px;color:var(--muted);font-weight:800}.mh-index-value{display:block;font-size:24px;line-height:1.15;margin-top:8px;font-variant-numeric:tabular-nums;letter-spacing:-.02em}.mh-index-change{display:flex;gap:9px;margin-top:9px;font-size:12px;font-weight:850;font-variant-numeric:tabular-nums}.mh-index-date{display:block;margin-top:7px;color:var(--muted);font-size:9px}
.mh-panel{padding:18px 20px}.mh-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:14px}.mh-head h3{margin:0;font-size:18px}.mh-head p{margin:5px 0 0;color:var(--muted);font-size:10px;line-height:1.6}.mh-head-meta{font-size:10px;color:var(--muted);white-space:nowrap}
.mh-tabs{display:inline-flex;border:1px solid var(--line);border-radius:9px;padding:3px;background:color-mix(in srgb,var(--paper) 86%,transparent);gap:2px}.mh-tab{border:0;background:transparent;color:var(--muted);border-radius:7px;padding:6px 10px;font-size:10px;font-weight:800;cursor:pointer}.mh-tab.active{background:var(--paper);color:var(--ink);box-shadow:var(--shadow)}
.mh-dist-bars{height:176px;display:grid;grid-template-columns:repeat(9,1fr);gap:8px;align-items:end;padding:6px 2px 0}.mh-dist-col{height:100%;display:grid;grid-template-rows:1fr auto;gap:7px;min-width:0}.mh-dist-bar-wrap{height:100%;display:flex;align-items:flex-end;justify-content:center}.mh-dist-bar{width:min(34px,72%);min-height:3px;border-radius:5px 5px 2px 2px;position:relative;box-shadow:inset 0 1px 0 rgba(255,255,255,.28)}.mh-dist-bar.up{background:var(--up)}.mh-dist-bar.down{background:var(--down)}.mh-dist-bar.flat{background:var(--compare)}.mh-dist-num{position:absolute;left:50%;transform:translateX(-50%);top:-18px;font-size:10px;font-weight:800;color:var(--ink);white-space:nowrap}.mh-dist-label{text-align:center;color:var(--muted);font-size:9px;white-space:nowrap}
.mh-ratio-row{display:grid;grid-template-columns:auto minmax(120px,1fr) auto;gap:10px;align-items:center;margin-top:14px}.mh-ratio-label{font-size:11px;color:var(--muted);white-space:nowrap}.mh-ratio-label b{font-size:12px}.mh-ratio-track{height:13px;border-radius:999px;overflow:hidden;display:flex;background:var(--line)}.mh-ratio-down{background:var(--down)}.mh-ratio-flat{background:var(--compare)}.mh-ratio-up{background:var(--up)}
.mh-board-list{display:grid}.mh-board-row{display:grid;grid-template-columns:minmax(120px,1.45fr) .75fr .75fr .65fr;gap:12px;align-items:center;padding:12px 4px;border-top:1px solid var(--line);cursor:pointer}.mh-board-row:first-child{border-top:0}.mh-board-row:hover{background:color-mix(in srgb,var(--blue2) 48%,transparent)}.mh-board-name strong{display:block;font-size:13px}.mh-board-name span{display:block;margin-top:4px;color:var(--muted);font-size:9px}.mh-board-cell{text-align:right;font-size:11px;color:var(--muted);font-variant-numeric:tabular-nums}.mh-board-cell b{color:var(--ink);font-size:12px}.mh-streak.up{color:var(--up)}.mh-streak.down{color:var(--down)}.mh-board-ret{font-size:14px!important}
.mh-board-head{display:grid;grid-template-columns:minmax(120px,1.45fr) .75fr .75fr .65fr;gap:12px;padding:0 4px 8px;color:var(--muted);font-size:9px}.mh-board-head span:not(:first-child){text-align:right}
.mh-more{border:0;background:transparent;color:var(--blue);font-size:10px;font-weight:850;cursor:pointer}
.mh-bottom{display:grid;grid-template-columns:1.2fr .8fr;gap:14px}.mh-fav-preview{display:grid;gap:7px}.mh-fav-row{border:1px solid var(--line);background:var(--paper);border-radius:10px;padding:10px 11px;display:grid;grid-template-columns:1fr auto auto;gap:10px;align-items:center;cursor:pointer}.mh-fav-row:hover{background:var(--blue2)}.mh-fav-row strong{font-size:11px}.mh-fav-row span{font-size:9px;color:var(--muted)}.mh-fav-row b{font-size:10px;font-variant-numeric:tabular-nums}.mh-empty{padding:22px;text-align:center;color:var(--muted);font-size:10px;border:1px dashed var(--line);border-radius:10px}
.mh-shortcuts{display:grid;grid-template-columns:1fr 1fr;gap:8px}.mh-shortcut{border:1px solid var(--line);background:var(--paper);color:var(--ink);border-radius:11px;padding:12px;cursor:pointer;text-align:left}.mh-shortcut:hover{border-color:var(--blue);background:var(--blue2)}.mh-shortcut strong{display:block;font-size:11px}.mh-shortcut span{display:block;margin-top:5px;color:var(--muted);font-size:9px;line-height:1.45}
#homeTrendPanel{order:99}.home-trend-wrap{height:270px}.home-trend-head h3{font-size:16px}
@media(max-width:1050px){.mh-index-strip{grid-template-columns:repeat(2,1fr)}.mh-bottom{grid-template-columns:1fr}.mh-board-row,.mh-board-head{grid-template-columns:minmax(110px,1.4fr) .7fr .7fr .65fr}}
@media(max-width:760px){#homePanel{gap:11px}.mh-index-strip{display:flex;overflow-x:auto;scroll-snap-type:x mandatory;gap:9px;padding-bottom:2px}.mh-index-strip::-webkit-scrollbar{display:none}.mh-index-card{min-width:190px;scroll-snap-align:start;padding:14px}.mh-index-value{font-size:22px}.mh-panel{padding:15px 13px}.mh-head{margin-bottom:12px}.mh-dist-bars{height:150px;gap:4px}.mh-dist-bar{width:min(26px,80%)}.mh-dist-label{font-size:8px}.mh-ratio-row{gap:7px}.mh-board-head{display:none}.mh-board-row{grid-template-columns:minmax(105px,1.25fr) .72fr .72fr;padding:11px 2px;gap:7px}.mh-board-row .mh-board-cell:nth-child(2){display:none}.mh-board-name strong{font-size:12px}.mh-board-ret{font-size:13px!important}.mh-shortcuts{grid-template-columns:1fr 1fr}.home-trend-wrap{height:235px}}
"""

JS = r"""
// MARKET_HOME_DASHBOARD
let mhDistributionKind='sector';
let mhBoardSort='return';
function mhEsc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function mhRows(obj){return (obj?.history||[]).filter(r=>Array.isArray(r)&&r.length>=2&&r[0]&&Number.isFinite(Number(r[1]))&&Number(r[1])>0).map(r=>[String(r[0]),Number(r[1])]).sort((a,b)=>a[0].localeCompare(b[0]))}
function mhDay(obj){const r=mhRows(obj);if(r.length<2)return null;const a=r[r.length-2],b=r[r.length-1];return{date:b[0],value:b[1],prev:a[1],delta:b[1]-a[1],ret:(b[1]/a[1]-1)*100}}
function mhSigned(v,d=2){if(!Number.isFinite(v))return '—';return `${v>0?'+':''}${v.toFixed(d)}`}
function mhPct(v,d=2){if(!Number.isFinite(v))return '—';return `${v>0?'+':''}${v.toFixed(d)}%`}
function mhCls(v){return Number.isFinite(v)?(v>0?'up':v<0?'down':''):''}
function mhStreak(obj){const r=mhRows(obj);if(r.length<2)return{n:0,dir:0,label:'—'};const signs=[];for(let i=r.length-1;i>0;i--){const d=r[i][1]-r[i-1][1];signs.push(d>0?1:d<0?-1:0)}const dir=signs[0]||0;if(!dir)return{n:0,dir:0,label:'平盘'};let n=0;for(const s of signs){if(s!==dir)break;n++}return{n,dir,label:`连${dir>0?'涨':'跌'}${n}天`}}
function mhFundUniverse(){const m=new Map();(sectors||[]).forEach(s=>(s?.funds||[]).forEach(f=>{const k=String(f?.code||f?.name||'');if(k&&!m.has(k))m.set(k,f)}));return[...m.values()]}
function mhIndexCard(name){const s=(sectors||[]).find(x=>x?.name===name),d=mhDay(s);if(!s||!d)return'';return `<button class="mh-index-card" type="button" onclick="selectSector('${mhEsc(name)}',true)"><span class="mh-index-name">${mhEsc(name)}</span><strong class="mh-index-value ${mhCls(d.ret)}">${d.value.toFixed(2)}</strong><span class="mh-index-change ${mhCls(d.ret)}"><b>${mhSigned(d.delta,2)}</b><b>${mhPct(d.ret,2)}</b></span><small class="mh-index-date">数据截至 ${mhEsc(d.date)}</small></button>`}
function mhBuckets(values){const b=[0,0,0,0,0,0,0,0,0];values.forEach(v=>{if(v<=-5)b[0]++;else if(v<=-3)b[1]++;else if(v<=-1)b[2]++;else if(v<-.005)b[3]++;else if(Math.abs(v)<=.005)b[4]++;else if(v<1)b[5]++;else if(v<3)b[6]++;else if(v<5)b[7]++;else b[8]++});return b}
function mhDistributionValues(){const objs=mhDistributionKind==='fund'?mhFundUniverse():(sectors||[]);return objs.map(x=>mhDay(x)).filter(Boolean)}
function mhRenderDistribution(){const rows=mhDistributionValues(),vals=rows.map(x=>x.ret).filter(Number.isFinite),b=mhBuckets(vals),max=Math.max(1,...b),labels=['≤-5','-5~-3','-3~-1','-1~0','0','0~1','1~3','3~5','≥5'];const bars=document.getElementById('mhDistBars');if(bars)bars.innerHTML=b.map((n,i)=>`<div class="mh-dist-col"><div class="mh-dist-bar-wrap"><div class="mh-dist-bar ${i<4?'down':i===4?'flat':'up'}" style="height:${Math.max(3,n/max*100)}%"><span class="mh-dist-num">${n}</span></div></div><div class="mh-dist-label">${labels[i]}</div></div>`).join('');const down=vals.filter(v=>v<-.005).length,flat=vals.filter(v=>Math.abs(v)<=.005).length,up=vals.filter(v=>v>.005).length,total=Math.max(1,down+flat+up);const ratio=document.getElementById('mhRatio');if(ratio)ratio.innerHTML=`<span class="mh-ratio-label">下跌 <b class="down">${down}</b></span><div class="mh-ratio-track"><i class="mh-ratio-down" style="width:${down/total*100}%"></i><i class="mh-ratio-flat" style="width:${flat/total*100}%"></i><i class="mh-ratio-up" style="width:${up/total*100}%"></i></div><span class="mh-ratio-label"><b class="up">${up}</b> 上涨</span>`;const latest=rows.map(x=>x.date).sort().slice(-1)[0];const meta=document.getElementById('mhDistMeta');if(meta)meta.textContent=`${mhDistributionKind==='fund'?'ETF':'板块'} · ${latest||'—'}`}
function mhSectorRows(){return(sectors||[]).map(s=>{const d=mhDay(s),st=mhStreak(s);return{s,d,st,funds:(s?.funds||[]).length}}).filter(x=>x.d)}
function mhRenderBoard(){let rows=mhSectorRows();if(mhBoardSort==='streak')rows.sort((a,b)=>(b.st.dir*b.st.n)-(a.st.dir*a.st.n)||b.d.ret-a.d.ret);else if(mhBoardSort==='favorites'){const fav=(typeof srFavorites!=='undefined'?srFavorites:new Set());rows.sort((a,b)=>(fav.has(b.s.name)?1:0)-(fav.has(a.s.name)?1:0)||b.d.ret-a.d.ret)}else rows.sort((a,b)=>b.d.ret-a.d.ret);rows=rows.slice(0,10);const box=document.getElementById('mhBoardList');if(box)box.innerHTML=rows.map(x=>`<div class="mh-board-row" data-mh-sector="${mhEsc(x.s.name)}"><div class="mh-board-name"><strong>${mhEsc(x.s.name)}</strong><span>${mhEsc(x.s.benchmark||'')}</span></div><div class="mh-board-cell"><span>关联ETF</span><br><b>${x.funds}</b></div><div class="mh-board-cell"><b class="mh-streak ${x.st.dir>0?'up':x.st.dir<0?'down':''}">${x.st.label}</b></div><div class="mh-board-cell"><b class="mh-board-ret ${mhCls(x.d.ret)}">${mhPct(x.d.ret,2)}</b></div></div>`).join('');box?.querySelectorAll('[data-mh-sector]').forEach(r=>r.onclick=()=>selectSector(r.dataset.mhSector,true))}
function mhRenderFavoritesPreview(){const box=document.getElementById('mhFavPreview');if(!box)return;const names=typeof srFavoriteNames==='function'?srFavoriteNames().slice(0,5):[];if(!names.length){box.innerHTML='<div class="mh-empty">还没有自选板块，可在“全部板块 → 管理板块”里点 ☆ 添加。</div>';return}box.innerHTML=names.map(n=>{const s=(sectors||[]).find(x=>String(x?.name||'')===n),d=mhDay(s),st=mhStreak(s);return `<button class="mh-fav-row" type="button" data-mh-fav="${mhEsc(n)}"><strong>${mhEsc(n)}</strong><span class="${st.dir>0?'up':st.dir<0?'down':''}">${st.label}</span><b class="${mhCls(d?.ret)}">${d?mhPct(d.ret,2):'—'}</b></button>`}).join('');box.querySelectorAll('[data-mh-fav]').forEach(b=>b.onclick=()=>selectSector(b.dataset.mhFav,true))}
function mhMarkup(){return `<section class="mh-index-strip" id="mhIndexStrip"></section><section class="panel mh-panel"><div class="mh-head"><div><h3>涨跌分布</h3><p>用当天涨跌区间观察市场温度；可在板块和ETF样本之间切换。</p></div><div><div class="mh-tabs"><button class="mh-tab ${mhDistributionKind==='sector'?'active':''}" data-mh-dist="sector">板块</button><button class="mh-tab ${mhDistributionKind==='fund'?'active':''}" data-mh-dist="fund">ETF</button></div><div class="mh-head-meta" id="mhDistMeta" style="margin-top:6px;text-align:right">—</div></div></div><div class="mh-dist-bars" id="mhDistBars"></div><div class="mh-ratio-row" id="mhRatio"></div></section><section class="panel mh-panel"><div class="mh-head"><div><h3>板块总览</h3><p>默认按当日涨跌展示，连续涨跌仅描述近期价格行为，不代表投资排序。</p></div><button class="mh-more" type="button" onclick="openNavPage('all')">全部板块 ›</button></div><div class="mh-tabs" style="margin-bottom:10px"><button class="mh-tab ${mhBoardSort==='return'?'active':''}" data-mh-sort="return">当日涨跌</button><button class="mh-tab ${mhBoardSort==='streak'?'active':''}" data-mh-sort="streak">连续涨跌</button><button class="mh-tab ${mhBoardSort==='favorites'?'active':''}" data-mh-sort="favorites">自选优先</button></div><div class="mh-board-head"><span>板块</span><span>ETF样本</span><span>连续状态</span><span>当日涨跌</span></div><div class="mh-board-list" id="mhBoardList"></div></section><div class="mh-bottom"><section class="panel mh-panel"><div class="mh-head"><div><h3>自选观察</h3><p>快速检查你加星板块的当日表现和连续状态。</p></div><button class="mh-more" type="button" onclick="openNavPage('favorites')">查看全部 ›</button></div><div class="mh-fav-preview" id="mhFavPreview"></div></section><section class="panel mh-panel"><div class="mh-head"><div><h3>研究入口</h3><p>从行情总览进入更详细的研究页面。</p></div></div><div class="mh-shortcuts"><button class="mh-shortcut" onclick="openNavPage('market')"><strong>状态变化</strong><span>近5/20日趋势与RS变化</span></button><button class="mh-shortcut" onclick="openNavPage('etf')"><strong>ETF研究</strong><span>规模、成交额、费率与跟踪指数</span></button><button class="mh-shortcut" onclick="openNavPage('all')"><strong>全部板块</strong><span>浏览完整二级板块目录</span></button><button class="mh-shortcut" onclick="openNavPage('favorites')"><strong>自选观察</strong><span>集中查看常看的板块</span></button></div></section></div>`}
function renderMarketHome(){const home=document.getElementById('homePanel');if(!home)return;home.innerHTML=mhMarkup();const strip=document.getElementById('mhIndexStrip');if(strip)strip.innerHTML=['沪深300','中证500','创业板','科创板'].map(mhIndexCard).join('');home.querySelectorAll('[data-mh-dist]').forEach(b=>b.onclick=()=>{mhDistributionKind=b.dataset.mhDist;renderMarketHome()});home.querySelectorAll('[data-mh-sort]').forEach(b=>b.onclick=()=>{mhBoardSort=b.dataset.mhSort;renderMarketHome()});mhRenderDistribution();mhRenderBoard();mhRenderFavoritesPreview();if(typeof renderHomeTrend==='function'){renderHomeTrend();const t=document.getElementById('homeTrendPanel');if(t){const h=t.querySelector('h3'),p=t.querySelector('.home-trend-head p');if(h)h.textContent='主要指数相对趋势';if(p)p.textContent='所选周期起点归一为0%，用于比较中期相对强弱。';home.appendChild(t)}}}
renderHome=renderMarketHome;
setTimeout(()=>{if(typeof navPage!=='undefined'&&navPage==='home')renderMarketHome()},0);
"""

def main():
    text = INDEX.read_text(encoding="utf-8")
    if MARKER in text:
        print("[skip] market homepage already installed")
        return
    if "HOME_TREND_CHART" not in text or "SECTOR_FAVORITES_WATCHLIST" not in text:
        raise RuntimeError("homepage trend and favorites patches must run first")
    if "</body>" not in text:
        raise RuntimeError("body marker missing")
    patch = f"\n<style>{CSS}</style>\n<script>{JS}</script>\n<!-- {MARKER} -->\n"
    text = text.replace("</body>", patch + "</body>", 1)
    INDEX.write_text(text, encoding="utf-8")
    print("[done] mobile-first market homepage installed")

if __name__ == "__main__":
    main()
