#!/usr/bin/env python3
"""Add primary/secondary navigation and a compact homepage dashboard."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "docs" / "index.html"
MARKER = "NAV_HOME_UI"

CSS = r'''
/* NAV_HOME_UI */
.side-title{padding-top:12px}.primary-nav{display:flex;flex-direction:column;gap:5px}.primary-item{width:100%;border:0;background:transparent;color:#c8d1df;border-radius:9px;padding:10px 11px;cursor:pointer;display:flex;align-items:center;justify-content:space-between;text-align:left;font-size:12px;font-weight:800}.primary-item:hover{background:rgba(255,255,255,.06);color:#fff}.primary-item.active{background:linear-gradient(90deg,color-mix(in srgb,var(--blue) 40%,transparent),transparent);color:#fff;box-shadow:inset 2px 0 0 var(--blue)}.primary-main{display:flex;align-items:center;gap:9px}.primary-icon{width:23px;height:23px;border-radius:7px;display:grid;place-items:center;background:rgba(255,255,255,.06);font-size:11px}.primary-meta{font-size:10px;color:#7f8ca3;font-weight:700}.primary-caret{font-size:11px;color:#8291a8;transition:transform .2s}.primary-item.expanded .primary-caret{transform:rotate(90deg)}.sector-subnav{margin:2px 0 7px 13px;padding:3px 0 4px 10px;border-left:1px solid rgba(255,255,255,.09);display:flex;flex-direction:column;gap:2px}.sector-subnav[hidden]{display:none}.sector-subnav button{padding:7px 9px!important;font-size:11px!important;border-radius:7px!important}.sector-subnav button.active{background:color-mix(in srgb,var(--blue) 32%,transparent)!important;box-shadow:inset 2px 0 0 var(--blue)!important}.mobile-primary{display:none;margin-bottom:8px}.mobile-primary select{width:100%;padding:11px;border:1px solid var(--line);border-radius:10px;background:var(--paper);color:var(--ink)}
body[data-nav-page] #homePanel,body[data-nav-page] #sectorDirectoryPanel,body[data-nav-page] #marketRadarPanel,body[data-nav-page] #radarChangePanel,body[data-nav-page] #researchHero,body[data-nav-page] #etfTerminalPanel,body[data-nav-page] .detail-workspace{display:none!important}
body[data-nav-page="home"] #homePanel{display:block!important}body[data-nav-page="all"] #sectorDirectoryPanel{display:block!important}body[data-nav-page="market"] #marketRadarPanel,body[data-nav-page="market"] #radarChangePanel{display:block!important}body[data-nav-page="etf"] #researchHero,body[data-nav-page="etf"] #etfTerminalPanel{display:block!important}body[data-nav-page="sector"] .detail-workspace{display:block!important}
.home-shell{display:grid;gap:14px}.home-hero{padding:22px}.home-hero-top{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}.home-hero h3{margin:4px 0 7px;font-size:24px;letter-spacing:-.03em}.home-hero p{margin:0;color:var(--muted);font-size:12px;line-height:1.75;max-width:720px}.home-date{font-size:11px;color:var(--muted);white-space:nowrap}.home-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:16px}.home-kpi{border:1px solid var(--line);background:var(--paper);border-radius:11px;padding:12px}.home-kpi span{display:block;color:var(--muted);font-size:10px}.home-kpi strong{display:block;margin-top:5px;font-size:21px;font-variant-numeric:tabular-nums}.home-grid{display:grid;grid-template-columns:1.05fr .95fr;gap:14px}.home-panel{padding:18px 20px}.home-panel h3{margin:0 0 5px;font-size:16px}.home-panel-sub{color:var(--muted);font-size:11px;margin-bottom:12px}.home-shortcuts{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.home-shortcut{border:1px solid var(--line);background:var(--paper);color:var(--ink);border-radius:11px;padding:13px;cursor:pointer;text-align:left}.home-shortcut:hover{border-color:var(--blue);background:var(--blue2)}.home-shortcut strong{display:block;font-size:12px}.home-shortcut span{display:block;color:var(--muted);font-size:10px;line-height:1.55;margin-top:5px}.home-events{display:grid;gap:6px}.home-event{border:1px solid var(--line);background:var(--paper);border-radius:9px;padding:9px 10px;cursor:pointer;display:grid;grid-template-columns:90px 1fr auto;gap:8px;align-items:center}.home-event:hover{background:var(--blue2)}.home-event strong{font-size:11px}.home-event span{font-size:10px;color:var(--muted);line-height:1.45}.home-event em{font-style:normal;font-size:9px;color:var(--blue);font-weight:800}.sector-directory{padding:18px 20px}.sector-directory-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:12px}.sector-directory-head h3{margin:0;font-size:18px}.sector-directory-head p{margin:5px 0 0;color:var(--muted);font-size:11px}.sector-directory-count{font-size:11px;color:var(--muted)}.sector-directory-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.sector-card{border:1px solid var(--line);background:var(--paper);border-radius:10px;padding:11px 12px;cursor:pointer;text-align:left;color:var(--ink)}.sector-card:hover{border-color:var(--blue);background:var(--blue2)}.sector-card-top{display:flex;justify-content:space-between;gap:8px;align-items:center}.sector-card strong{font-size:12px}.sector-card-state{font-size:9px;color:var(--muted)}.sector-card-meta{margin-top:7px;font-size:10px;color:var(--muted);display:flex;justify-content:space-between;gap:8px}.sector-card-meta b{font-weight:800;color:var(--ink)}
@media(max-width:1100px){.sector-directory-grid{grid-template-columns:repeat(3,1fr)}.home-grid{grid-template-columns:1fr}.home-kpis{grid-template-columns:repeat(2,1fr)}}
@media(max-width:760px){.mobile-primary{display:block}.home-hero{padding:17px}.home-hero-top{display:block}.home-date{margin-top:8px}.home-kpis{grid-template-columns:1fr 1fr}.home-shortcuts{grid-template-columns:1fr}.sector-directory-grid{grid-template-columns:1fr 1fr}.home-event{grid-template-columns:72px 1fr}.home-event em{display:none}body[data-nav-page="home"] .mobile-select,body[data-nav-page="market"] .mobile-select,body[data-nav-page="etf"] .mobile-select{display:none}}
@media(max-width:460px){.sector-directory-grid{grid-template-columns:1fr}}
'''

PANELS = r'''
    <!-- NAV_HOME_UI -->
    <section class="home-shell" id="homePanel">
      <section class="panel home-hero"><div class="home-hero-top"><div><div class="eyebrow">MARKET OVERVIEW</div><h3>市场总览</h3><p>从全市场状态进入板块详情：先看覆盖范围与趋势结构，再看近期状态变化，最后进入具体板块和ETF研究。</p></div><div class="home-date" id="homeLatest">—</div></div><div class="home-kpis"><div class="home-kpi"><span>覆盖板块</span><strong id="homeCoverage">—</strong></div><div class="home-kpi"><span>中期偏强</span><strong id="homeTrend">—</strong></div><div class="home-kpi"><span>RS60跑赢沪深300</span><strong id="homeRS">—</strong></div><div class="home-kpi"><span>近5日状态变化</span><strong id="homeEventsCount">—</strong></div></div></section>
      <div class="home-grid"><section class="panel home-panel"><h3>快速进入</h3><div class="home-panel-sub">一级目录保持少而清晰，详细板块放在“全部板块”下。</div><div class="home-shortcuts"><button class="home-shortcut" type="button" onclick="openNavPage('all')"><strong>全部板块</strong><span>浏览全部板块，并进入二级板块详情。</span></button><button class="home-shortcut" type="button" onclick="openNavPage('market')"><strong>状态变化</strong><span>查看轮动雷达与近5/20日状态切换。</span></button><button class="home-shortcut" type="button" onclick="openNavPage('etf')"><strong>ETF研究</strong><span>比较规模、成交额、费率、跟踪指数与同期表现。</span></button></div></section><section class="panel home-panel"><h3>最近状态变化</h3><div class="home-panel-sub">按事件优先级展示最近5个交易日发生变化的板块，不代表投资排序。</div><div class="home-events" id="homeEvents"><div class="loading">正在读取…</div></div></section></div>
    </section>
    <section class="panel sector-directory" id="sectorDirectoryPanel"><div class="sector-directory-head"><div><h3>全部板块</h3><p>左侧“全部板块”为一级目录，下面所有板块均为二级目录。</p></div><div class="sector-directory-count" id="sectorDirectoryCount">—</div></div><div class="sector-directory-grid" id="sectorDirectoryGrid"></div></section>
'''

MOBILE = r'''<div class="mobile-primary"><select id="mobilePrimaryNav" aria-label="一级目录"><option value="home">首页</option><option value="all">全部板块</option><option value="market">状态变化</option><option value="etf">ETF研究</option></select></div>'''

JS = r'''
// NAV_HOME_UI
let navPage='home',navAllExpanded=true;
function navText(id,text){const e=document.getElementById(id);if(e)e.textContent=text}
function setNavHeader(title,sub,eyebrow){const h=document.getElementById('pageTitle')||document.querySelector('.topbar h2'),p=document.getElementById('pageSubtitle')||document.querySelector('.topbar .subtitle'),e=document.querySelector('.topbar .eyebrow');if(h)h.textContent=title;if(p)p.textContent=sub;if(e)e.textContent=eyebrow}
function sectorEventRows(){const rows=[];(sectors||[]).forEach(s=>(s?.radar2?.events_5d||[]).forEach(ev=>rows.push({s,ev})));return rows.sort((a,b)=>(b.ev.priority||0)-(a.ev.priority||0)||String(a.s.name).localeCompare(String(b.s.name),'zh-CN'))}
function renderHome(){const payload=window.__latestPayload||{},summary=payload.radar_summary||{},r2=payload.radar2_summary||{};navText('homeCoverage',String((sectors||[]).length));navText('homeTrend',summary.trend_positive??'—');navText('homeRS',summary.rs60_positive??'—');navText('homeEventsCount',r2.event_sectors_5d??'—');const latest=(sectors||[]).map(s=>s.latest_date).filter(Boolean).sort().slice(-1)[0];navText('homeLatest',latest?`数据截至 ${latest}`:'数据日期 —');const box=document.getElementById('homeEvents');if(box){const rows=sectorEventRows().slice(0,6);box.innerHTML=rows.length?rows.map(x=>`<button class="home-event" type="button" onclick="selectSector('${esc(x.s.name)}',true)"><strong>${esc(x.s.name)}</strong><span>${esc(x.ev.label||'状态发生变化')}</span><em>${x.ev.direction==='up'?'上行变化':x.ev.direction==='down'?'下行变化':'状态变化'}</em></button>`).join(''):'<div class="radar-event-empty">近5个交易日暂无主要状态变化</div>'}}
function renderSectorDirectory(){const grid=document.getElementById('sectorDirectoryGrid');if(!grid)return;navText('sectorDirectoryCount',`${(sectors||[]).length} 个板块`);grid.innerHTML=(sectors||[]).map(s=>{const r=s.radar||{},state=r.trend_state||s?.radar2?.current?.trend_state||'—',rs=Number(r.rs60);return `<button class="sector-card" type="button" onclick="selectSector('${esc(s.name)}',true)"><div class="sector-card-top"><strong>${esc(s.name)}</strong><span class="sector-card-state">${esc(state)}</span></div><div class="sector-card-meta"><span>RS60</span><b>${Number.isFinite(rs)?(rs>=0?'+':'')+rs.toFixed(1)+'%':'—'}</b></div></button>`}).join('')}
function applyNavVisibility(){document.body.dataset.navPage=navPage;const m=document.getElementById('mobilePrimaryNav');if(m)m.value=navPage==='sector'?'all':navPage;if(navPage==='home'){setNavHeader('首页 · 市场总览','先看市场结构与最近状态变化，再进入板块详情或ETF研究。','SECTOR RADAR / HOME');renderHome()}else if(navPage==='all'){setNavHeader('全部板块','全部板块为一级目录；点击左侧二级板块进入独立详情。','SECTOR DIRECTORY');renderSectorDirectory()}else if(navPage==='market'){setNavHeader('状态变化','观察全市场相对强弱、轮动位置和近5/20个交易日状态切换。','MARKET STATE / CHANGE');if(typeof renderMarketRadar==='function')renderMarketRadar();if(typeof renderRadarChanges==='function')renderRadarChanges()}else if(navPage==='etf'){setNavHeader('ETF研究','比较同主题ETF的规模、成交额、费率、跟踪指数与同期表现。','ETF RESEARCH');const hero=document.querySelector('#researchHero h3'),hp=document.querySelector('#researchHero p');if(hero)hero.textContent='ETF研究终端';if(hp)hp.textContent='进入具体板块后核对研究口径，再在这里比较同主题ETF的规模、流动性、费率、跟踪指数与同期表现。';if(typeof renderResearchSummary==='function')renderResearchSummary();if(typeof renderEtfTerminal==='function')renderEtfTerminal()}else{const n=activeSector?.name||'板块详情';setNavHeader(`${n} · 板块详情`,'查看长期走势、周期涨跌、研究口径和代表ETF。','SECTOR DETAIL')}}
function openNavPage(page){navPage=['home','all','market','etf','sector'].includes(page)?page:'home';if(navPage==='all')navAllExpanded=true;applyNavVisibility();buildMenu();window.scrollTo({top:0,behavior:'smooth'})}
function buildMenu(){const q=(document.getElementById('sideSearch')?.value||'').trim().toLowerCase(),menu=document.getElementById('menu');if(!menu)return;const filtered=(sectors||[]).filter(s=>(String(s.name||'')+' '+String(s.benchmark||'')).toLowerCase().includes(q));if(q)navAllExpanded=true;const r2=window.__latestPayload?.radar2_summary||{},meta=window.__latestPayload?.etf_metadata_summary||{};menu.innerHTML=`<div class="primary-nav"><button class="primary-item ${navPage==='home'?'active':''}" type="button" data-primary="home"><span class="primary-main"><span class="primary-icon">⌂</span>首页</span></button><button class="primary-item ${(navPage==='all'||navPage==='sector')?'active':''} ${navAllExpanded?'expanded':''}" type="button" data-primary="all"><span class="primary-main"><span class="primary-icon">▦</span>全部板块</span><span><span class="primary-meta">${(sectors||[]).length}</span> <span class="primary-caret">›</span></span></button><div class="sector-subnav" id="sectorSubnav" ${navAllExpanded?'':'hidden'}></div><button class="primary-item ${navPage==='market'?'active':''}" type="button" data-primary="market"><span class="primary-main"><span class="primary-icon">↗</span>状态变化</span><span class="primary-meta">${r2.event_sectors_5d??'—'}</span></button><button class="primary-item ${navPage==='etf'?'active':''}" type="button" data-primary="etf"><span class="primary-main"><span class="primary-icon">◎</span>ETF研究</span><span class="primary-meta">${meta.profile_ok??''}</span></button></div>`;menu.querySelectorAll('[data-primary]').forEach(b=>b.onclick=()=>{const p=b.dataset.primary;if(p==='all'){navAllExpanded=!navAllExpanded;openNavPage('all')}else openNavPage(p)});const sub=document.getElementById('sectorSubnav');if(sub){sub.innerHTML=filtered.map(s=>`<button type="button" class="${navPage==='sector'&&s===activeSector?'active':''}" data-sector-name="${esc(s.name)}"><span>${esc(s.name)}</span><span class="mini">${s.status==='ok'?'●':s.status==='partial'?'◐':'○'}</span></button>`).join('')||(q?'<div class="loading">没有匹配板块</div>':'');sub.querySelectorAll('[data-sector-name]').forEach(b=>b.onclick=()=>selectSector(b.dataset.sectorName,true))}}
const navBaseSelectSector=selectSector;
selectSector=function(name,push){navBaseSelectSector(name,push);navPage='sector';navAllExpanded=true;applyNavVisibility();buildMenu()};
const navBaseBuildMobile=buildMobile;
buildMobile=function(){navBaseBuildMobile();const p=document.getElementById('mobilePrimaryNav');if(p){p.value=navPage==='sector'?'all':navPage;p.onchange=()=>openNavPage(p.value)}};
'''

def main():
    text = INDEX.read_text(encoding="utf-8")
    if MARKER in text:
        return
    if "</style>" not in text:
        raise RuntimeError("style marker missing")
    text = text.replace("</style>", CSS + "\n</style>", 1)
    text = text.replace('<h1>板块目录</h1><p>点击左侧板块进入独立详情视图</p>', '<h1>板块雷达</h1><p>首页、全部板块、状态变化与ETF研究</p>', 1)
    text = text.replace('<div class="side-search"><input id="sideSearch" placeholder="搜索板块"></div>', '<div class="side-search"><input id="sideSearch" placeholder="搜索二级板块"></div>', 1)
    text = text.replace('<div class="side-title">全部板块</div>', '<div class="side-title">导航</div>', 1)
    mobile_marker = '    <div class="mobile-select"><select id="mobileSector"></select></div>'
    if mobile_marker in text:
        text = text.replace(mobile_marker, '    ' + MOBILE + '\n' + mobile_marker, 1)
    else:
        raise RuntimeError("mobile selector marker missing")
    panel_marker = '    <section class="panel research-hero" id="researchHero">'
    if panel_marker not in text:
        panel_marker = '    <section class="panel radar-market" id="marketRadarPanel">'
    if panel_marker not in text:
        raise RuntimeError("research/market panel marker missing")
    text = text.replace(panel_marker, PANELS + "\n" + panel_marker, 1)
    js_marker = "$('#sideSearch').oninput=buildMenu;"
    if js_marker not in text:
        raise RuntimeError("JS insertion marker missing")
    text = text.replace(js_marker, JS + "\n" + js_marker, 1)
    text = text.replace("buildMenu();buildMobile();renderDetail();setWorkspace('detail')", "buildMenu();buildMobile();renderDetail();openNavPage('home')", 1)
    INDEX.write_text(text, encoding="utf-8")
    print("[done] hierarchical navigation + homepage installed")

if __name__ == "__main__":
    main()
