#!/usr/bin/env python3
"""Add Daily Economic News navigation and Nasdaq fund-limit dashboard."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "docs" / "index.html"
MARKER = "NEWS_NASDAQ_LIMITS_UI"

CSS = r'''
/* NEWS_NASDAQ_LIMITS_UI */
.sr-news-panel,.sr-limit-panel{display:none;margin-bottom:14px}
body[data-nav-page="news"] #srNewsPanel{display:block!important}
body[data-nav-page="nasdaq-limits"] #srNasdaqLimitsPanel{display:block!important}
.news-subnav{margin:2px 0 7px 13px;padding:3px 0 4px 10px;border-left:1px solid rgba(255,255,255,.09);display:flex;flex-direction:column;gap:2px}.news-subnav[hidden]{display:none}.news-subnav button{padding:7px 9px!important;font-size:11px!important;border-radius:7px!important}.news-subnav button.active{background:color-mix(in srgb,var(--blue) 32%,transparent)!important;box-shadow:inset 2px 0 0 var(--blue)!important}.nasdaq-limit-entry{margin-left:17px!important;width:calc(100% - 17px)!important;color:#a9c0ff!important}.nasdaq-limit-entry:before{content:'↳';margin-right:6px;color:#7e9af0}.nasdaq-limit-entry.active{background:color-mix(in srgb,var(--blue) 30%,transparent)!important;color:#fff!important}
.sr-news-wrap,.sr-limit-wrap{padding:18px 20px}.sr-section-head{display:flex;justify-content:space-between;align-items:flex-start;gap:14px;margin-bottom:14px}.sr-section-head h3{margin:0;font-size:19px}.sr-section-head p{margin:5px 0 0;color:var(--muted);font-size:11px;line-height:1.65}.sr-data-time{font-size:10px;color:var(--muted);white-space:nowrap}.sr-news-tabs,.sr-limit-filters{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:13px}.sr-chip{border:1px solid var(--line);background:var(--paper);color:var(--muted);border-radius:999px;padding:7px 11px;font-size:10px;font-weight:800;cursor:pointer}.sr-chip.active{border-color:var(--blue);background:var(--blue2);color:var(--blue)}
.sr-news-list{display:grid;gap:8px}.sr-news-item{display:grid;grid-template-columns:82px minmax(0,1fr) auto;gap:10px;align-items:center;border:1px solid var(--line);background:var(--paper);border-radius:10px;padding:11px 12px;text-decoration:none;color:var(--ink)}.sr-news-item:hover{border-color:var(--blue);background:var(--blue2)}.sr-news-date{font-size:9px;color:var(--muted);font-variant-numeric:tabular-nums}.sr-news-title{font-size:11px;font-weight:800;line-height:1.55}.sr-news-source{font-size:9px;color:var(--blue);font-weight:800}.sr-news-empty{padding:28px;text-align:center;color:var(--muted);border:1px dashed var(--line);border-radius:10px;font-size:11px}
.sr-limit-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:13px}.sr-limit-kpi{border:1px solid var(--line);background:var(--paper);border-radius:10px;padding:10px 11px}.sr-limit-kpi span{display:block;color:var(--muted);font-size:9px}.sr-limit-kpi strong{display:block;font-size:18px;margin-top:4px}.sr-limit-search{margin-left:auto;min-width:220px;border:1px solid var(--line);background:var(--paper);color:var(--ink);border-radius:9px;padding:8px 10px;font-size:10px}.sr-limit-table-wrap{overflow:auto;border:1px solid var(--line);border-radius:11px}.sr-limit-table{width:100%;border-collapse:collapse;min-width:760px;font-size:10px}.sr-limit-table th,.sr-limit-table td{padding:10px 11px;border-bottom:1px solid var(--line);text-align:left;vertical-align:middle}.sr-limit-table th{position:sticky;top:0;background:var(--paper);color:var(--muted);font-size:9px;z-index:1}.sr-limit-table tr:last-child td{border-bottom:0}.sr-limit-name{font-weight:800;color:var(--ink)}.sr-limit-code{font-size:9px;color:var(--muted);margin-top:2px}.sr-status{display:inline-flex;border-radius:999px;padding:4px 7px;font-size:9px;font-weight:850;border:1px solid var(--line)}.sr-status.open{color:#087443;background:#ecfdf3;border-color:#b7ebcf}.sr-status.limit{color:#8a6100;background:#fff7d6;border-color:#ead58a}.sr-status.pause{color:#a33a31;background:#fff1f0;border-color:#f2c7c3}.sr-status.unknown{color:var(--muted)}.sr-limit-amt{font-weight:850;font-variant-numeric:tabular-nums}.sr-limit-link{color:var(--blue);font-weight:800;text-decoration:none}.sr-limit-note{margin-top:10px;font-size:9px;color:var(--muted);line-height:1.65}
@media(max-width:760px){.sr-news-wrap,.sr-limit-wrap{padding:14px}.sr-section-head{display:block}.sr-data-time{margin-top:7px}.sr-news-item{grid-template-columns:70px 1fr}.sr-news-source{display:none}.sr-limit-kpis{grid-template-columns:1fr 1fr}.sr-limit-search{width:100%;min-width:0;margin-left:0}.sr-limit-filters{align-items:stretch}}
'''

PANELS = r'''
<section class="panel sr-news-panel" id="srNewsPanel"><div class="sr-news-wrap"><div class="sr-section-head"><div><h3>每日经济新闻</h3><p>聚合《每日经济新闻》公开报道，按科技、医药、机器人、煤炭分类。这里只做资讯整理，点击标题打开原文。</p></div><div class="sr-data-time" id="srNewsTime">—</div></div><div class="sr-news-tabs" id="srNewsTabs"></div><div class="sr-news-list" id="srNewsList"><div class="sr-news-empty">正在读取新闻…</div></div></div></section>
<section class="panel sr-limit-panel" id="srNasdaqLimitsPanel"><div class="sr-limit-wrap"><div class="sr-section-head"><div><h3>纳斯达克基金申购限额</h3><p>自动扫描名称包含“纳斯达克/纳指/NASDAQ”的人民币场外基金份额，展示当前公开申购状态与单日累计限额。纯场内ETF和美元份额不纳入此表。</p></div><div class="sr-data-time" id="srLimitTime">—</div></div><div class="sr-limit-kpis"><div class="sr-limit-kpi"><span>覆盖份额</span><strong id="srLimitTotal">—</strong></div><div class="sr-limit-kpi"><span>开放申购</span><strong id="srLimitOpen">—</strong></div><div class="sr-limit-kpi"><span>限大额</span><strong id="srLimitLimited">—</strong></div><div class="sr-limit-kpi"><span>暂停申购</span><strong id="srLimitPaused">—</strong></div></div><div class="sr-limit-filters"><button class="sr-chip active" type="button" data-limit-filter="all">全部</button><button class="sr-chip" type="button" data-limit-filter="open">开放</button><button class="sr-chip" type="button" data-limit-filter="limited">限额</button><button class="sr-chip" type="button" data-limit-filter="paused">暂停</button><input class="sr-limit-search" id="srLimitSearch" placeholder="搜索基金名称或代码"></div><div class="sr-limit-table-wrap"><table class="sr-limit-table"><thead><tr><th>基金</th><th>份额</th><th>申购状态</th><th>单日累计限额</th><th>最低申购</th><th>赎回</th><th>来源</th></tr></thead><tbody id="srLimitBody"><tr><td colspan="7">正在读取限额…</td></tr></tbody></table></div><div class="sr-limit-note" id="srLimitNote">数据来自天天基金/东方财富公开基金接口，每次网站构建时刷新。不同销售平台可能在基金公司限额基础上进一步收紧，实际可申购金额以下单页面和基金管理人公告为准。</div></div></section>
'''

JS = r'''
// NEWS_NASDAQ_LIMITS_UI
const srNewsCategories=['科技','医药','机器人','煤炭'];
let srNewsCategory=localStorage.getItem('sectorRadarNewsCategoryV1')||'科技';
if(!srNewsCategories.includes(srNewsCategory))srNewsCategory='科技';
let srNewsExpanded=localStorage.getItem('sectorRadarNewsExpandedV1')!=='0';
let srNewsData=null,srLimitsData=null,srLimitFilter='all';
function srFmtTime(v){if(!v)return'—';try{return new Date(v).toLocaleString('zh-CN',{hour12:false})}catch(_e){return String(v)}}
function srFmtMoney(v){const n=Number(v);if(!Number.isFinite(n))return'—';if(n>=100000000)return'不限额';if(n>=10000)return'¥'+(n/10000).toFixed(n>=100000?0:1)+'万';return'¥'+n.toLocaleString('zh-CN',{maximumFractionDigits:2})}
function srEnsureNewsPanels(){const top=document.querySelector('.topbar');if(!document.getElementById('srNewsPanel')){const box=document.createElement('div');box.innerHTML=`${PANELS_PLACEHOLDER}`;const nodes=[...box.children];nodes.reverse().forEach(n=>top?top.after(n):document.querySelector('.content')?.prepend(n))}}
'''.replace('${PANELS_PLACEHOLDER}', PANELS.replace('`','\\`').replace('${','\\${')) + r'''
function srLoadNews(){if(srNewsData)return Promise.resolve(srNewsData);return fetch('data/daily_news.json?ts='+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(x=>srNewsData=x).catch(()=>srNewsData={categories:{},updated_at:null,source:'每日经济新闻'})}
function srRenderNews(){srEnsureNewsPanels();const tabs=document.getElementById('srNewsTabs'),list=document.getElementById('srNewsList');if(!tabs||!list)return;tabs.innerHTML=srNewsCategories.map(c=>`<button class="sr-chip ${c===srNewsCategory?'active':''}" type="button" data-news-tab="${c}">${c}</button>`).join('');tabs.querySelectorAll('[data-news-tab]').forEach(b=>b.onclick=()=>{srNewsCategory=b.dataset.newsTab;try{localStorage.setItem('sectorRadarNewsCategoryV1',srNewsCategory)}catch(_e){};srRenderNews()});srLoadNews().then(data=>{const items=data?.categories?.[srNewsCategory]||[];document.getElementById('srNewsTime').textContent=data?.updated_at?'更新 '+srFmtTime(data.updated_at):'更新时间 —';list.innerHTML=items.length?items.map(x=>`<a class="sr-news-item" href="${srHtml(x.url||'#')}" target="_blank" rel="noopener noreferrer"><span class="sr-news-date">${srHtml(x.date||'最新')}</span><span class="sr-news-title">${srHtml(x.title||'')}</span><span class="sr-news-source">每经原文 ↗</span></a>`).join(''):'<div class="sr-news-empty">这个分类暂时没有抓到新的每经报道。</div>'})}
function srLimitStatusClass(s){return s==='暂停申购'?'pause':s==='限大额'?'limit':s==='开放申购'?'open':'unknown'}
function srLimitVisible(f){if(srLimitFilter==='open'&&f.status!=='开放申购')return false;if(srLimitFilter==='limited'&&f.status!=='限大额')return false;if(srLimitFilter==='paused'&&f.status!=='暂停申购')return false;const q=(document.getElementById('srLimitSearch')?.value||'').trim().toLowerCase();return !q||String(f.name||'').toLowerCase().includes(q)||String(f.code||'').includes(q)}
function srRenderLimitsTable(){const body=document.getElementById('srLimitBody');if(!body||!srLimitsData)return;const funds=(srLimitsData.funds||[]).filter(srLimitVisible);body.innerHTML=funds.length?funds.map(f=>`<tr><td><div class="sr-limit-name">${srHtml(f.name||'—')}</div><div class="sr-limit-code">${srHtml(f.code||'')}${f.note?' · '+srHtml(f.note):''}</div></td><td>${srHtml(f.share_class||'—')}</td><td><span class="sr-status ${srLimitStatusClass(f.status)}">${srHtml(f.status||'未知')}</span>${f.stale?'<div class="sr-limit-code">沿用上次值</div>':''}</td><td class="sr-limit-amt">${f.status==='暂停申购'?'—':srFmtMoney(f.max_buy)}</td><td>${srFmtMoney(f.min_buy)}</td><td>${srHtml(f.redemption_status||'—')}</td><td><a class="sr-limit-link" href="${srHtml(f.source_url||'#')}" target="_blank" rel="noopener noreferrer">天天基金 ↗</a></td></tr>`).join(''):'<tr><td colspan="7">没有匹配基金</td></tr>'}
function srLoadLimits(){if(srLimitsData)return Promise.resolve(srLimitsData);return fetch('data/nasdaq_limits.json?ts='+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(x=>srLimitsData=x).catch(()=>srLimitsData={funds:[],updated_at:null,count:0})}
function srRenderLimits(){srEnsureNewsPanels();srLoadLimits().then(data=>{const funds=data.funds||[];document.getElementById('srLimitTime').textContent=(data.fallback?'备用快照 · ':'')+(data.updated_at?'更新 '+srFmtTime(data.updated_at):'更新时间 —');document.getElementById('srLimitTotal').textContent=String(funds.length);document.getElementById('srLimitOpen').textContent=String(funds.filter(x=>x.status==='开放申购').length);document.getElementById('srLimitLimited').textContent=String(funds.filter(x=>x.status==='限大额').length);document.getElementById('srLimitPaused').textContent=String(funds.filter(x=>x.status==='暂停申购').length);document.querySelectorAll('[data-limit-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.limitFilter===srLimitFilter);b.onclick=()=>{srLimitFilter=b.dataset.limitFilter;srRenderLimits()}});const input=document.getElementById('srLimitSearch');if(input&&!input.dataset.bound){input.dataset.bound='1';input.oninput=srRenderLimitsTable}srRenderLimitsTable()})}
function srInstallNewsMobile(){const m=document.getElementById('mobilePrimaryNav');if(!m)return;if(!m.querySelector('option[value="news"]')){const o=document.createElement('option');o.value='news';o.textContent='每日经济新闻';const market=m.querySelector('option[value="market"]');market?m.insertBefore(o,market):m.appendChild(o)}if(navPage==='news')m.value='news';else if(navPage==='nasdaq-limits')m.value='all'}
function srOpenNewsCategory(cat){if(srNewsCategories.includes(cat))srNewsCategory=cat;try{localStorage.setItem('sectorRadarNewsCategoryV1',srNewsCategory)}catch(_e){};navPage='news';srNewsExpanded=true;try{localStorage.setItem('sectorRadarNewsExpandedV1','1')}catch(_e){};applyNavVisibility();buildMenu();window.scrollTo({top:0,behavior:'smooth'})}
const srNewsBaseApplyNavVisibility=applyNavVisibility;
applyNavVisibility=function(){if(navPage==='news'){document.body.dataset.navPage='news';srInstallNewsMobile();setNavHeader(`每日经济新闻 · ${srNewsCategory}`,'按行业主题查看《每日经济新闻》最新公开报道。','DAILY ECONOMIC NEWS');srRenderNews();return}if(navPage==='nasdaq-limits'){document.body.dataset.navPage='nasdaq-limits';srInstallNewsMobile();setNavHeader('纳斯达克 · 基金申购限额','查看纳斯达克相关人民币场外基金的最新公开申购状态和单日限额。','NASDAQ FUND QUOTA');srRenderLimits();return}srNewsBaseApplyNavVisibility()};
const srNewsBaseOpenNavPage=openNavPage;
openNavPage=function(page){if(page==='news'){srOpenNewsCategory(srNewsCategory);return}if(page==='nasdaq-limits'){navPage='nasdaq-limits';navAllExpanded=true;applyNavVisibility();buildMenu();window.scrollTo({top:0,behavior:'smooth'});return}srNewsBaseOpenNavPage(page)};
function srInstallNewsAndQuotaNav(){const primary=document.querySelector('#menu .primary-nav');if(!primary)return;primary.querySelector('[data-sr-news-primary]')?.remove();primary.querySelector('.news-subnav')?.remove();const market=primary.querySelector('[data-primary="market"]');const news=document.createElement('button');news.className=`primary-item ${navPage==='news'?'active':''} ${srNewsExpanded?'expanded':''}`;news.type='button';news.dataset.srNewsPrimary='1';news.innerHTML=`<span class="primary-main"><span class="primary-icon">闻</span>每日经济新闻</span><span><span class="primary-meta">NBD</span> <span class="primary-caret">›</span></span>`;const sub=document.createElement('div');sub.className='news-subnav';sub.hidden=!srNewsExpanded;sub.innerHTML=srNewsCategories.map(c=>`<button type="button" class="${navPage==='news'&&srNewsCategory===c?'active':''}" data-sr-news-cat="${c}"><span>${c}</span></button>`).join('');news.onclick=()=>{if(navPage==='news'){srNewsExpanded=!srNewsExpanded;try{localStorage.setItem('sectorRadarNewsExpandedV1',srNewsExpanded?'1':'0')}catch(_e){};buildMenu()}else srOpenNewsCategory(srNewsCategory)};sub.querySelectorAll('[data-sr-news-cat]').forEach(b=>b.onclick=()=>srOpenNewsCategory(b.dataset.srNewsCat));if(market){primary.insertBefore(news,market);primary.insertBefore(sub,market)}else{primary.append(news,sub)};const nasdaq=document.querySelector('#sectorSubnav [data-sector-name="纳斯达克"]');if(nasdaq){document.querySelectorAll('.nasdaq-limit-entry').forEach(x=>x.remove());const q=document.createElement('button');q.type='button';q.className=`nasdaq-limit-entry ${navPage==='nasdaq-limits'?'active':''}`;q.textContent='纳指基金限额';q.onclick=()=>openNavPage('nasdaq-limits');nasdaq.after(q);if(navPage==='nasdaq-limits')primary.querySelector('[data-primary="all"]')?.classList.add('active')}srInstallNewsMobile()}
const srNewsBaseBuildMenu=buildMenu;
buildMenu=function(){srNewsBaseBuildMenu();srInstallNewsAndQuotaNav()};
const srNewsBaseBuildMobile=buildMobile;
buildMobile=function(){srNewsBaseBuildMobile();srInstallNewsMobile();const p=document.getElementById('mobilePrimaryNav');if(p)p.onchange=()=>openNavPage(p.value)};
srEnsureNewsPanels();buildMenu();
'''


def main():
    text = INDEX.read_text(encoding="utf-8")
    if MARKER in text:
        print("[skip] news + Nasdaq limits UI already installed")
        return
    if "SECTOR_FAVORITES_WATCHLIST" not in text or "HOME_MARKET_RADAR_RESTORE" not in text:
        raise RuntimeError("navigation/favorites/home restore layers must be installed first")
    if "</body>" not in text:
        raise RuntimeError("body marker missing")
    patch = f"\n<style>{CSS}</style>\n<script>{JS}</script>\n<!-- {MARKER} -->\n"
    text = text.replace("</body>", patch + "</body>", 1)
    INDEX.write_text(text, encoding="utf-8")
    print("[done] Daily Economic News + Nasdaq fund limits navigation installed")


if __name__ == "__main__":
    main()
